databases:
  - name: db # Render PG14
    databaseName: db
    user: dbuser
    mongodbMajorVersion: 4

services:
  - type: web
    name: ws
    env: docker
    dockerfilePath: ./docker-compose.yml
    envVars:
      - key: ALLOW_EMPTY_PASSWORD
        value: 'yes'
      - key: MONGODB_ADVERTISED_HOSTNAME
        value: localhost
      - key: MONGODB_REPLICA_SET_MODE
        value: 'primary'
      - key: MONGODB_REPLICA_SET_NAME
        value: replicaset
      - key: MONGODB_EXTRA_FLAGS
        value: --bind_ip_all
